FROM alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
RUN wget -nv  https://agents.sealights.co/sl-cd-agent/sl-cd-agent-latest.zip
RUN unzip -oq sl-cd-agent-latest.zip
RUN rm sl-cd-agent-latest.zip