apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.11.2-4
      workingDir: /home/jenkins/agent
      resources:
        requests:
          cpu: 200m
          memory: 350Mi
          ephemeral-storage: 150Mi
        limits:
          cpu: 512m
          memory: 512Mi
          ephemeral-storage: 200Mi
      securityContext:
        privileged: true
    - name: shell
      image: public.ecr.aws/a2q7i5i2/sl-jenkins-base-ci:latest
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: 500Mi
          cpu: 0.5
          ephemeral-storage: 2000Mi
        limits:
          memory: 1000Mi
          cpu: 1
          ephemeral-storage: 10000Mi
